### ISSUE TITLE
Overlay Issue when keyboard close

### ISSUE THREAD

**Issue by moinkhan780** [Crazelu/fluttertagger#13] opened 2024-08-19 04:16 UTC
![Screenshot_1724040760](https://github.com/user-attachments/assets/42c287b0-332e-4b57-a9f0-14c40f51036c)

**Comment by Crazelu** [comment] 2024-08-30 23:30
@moinkhan780  can you add more context here so I can understand the issue?

**Comment by tiltmaster** [comment] 2024-12-01 11:23
> @moinkhan780 can you add more context here so I can understand the issue?

The issue is happeneing when a keyboard is opened, the list doesnt show exactly where it needs to be, upon keyboard close, the overlay does not move down, but rather stay up, causing a weird UI look as displayed above.

**Comment by sangilipandian** [comment] 2024-12-18 17:44
Im planning to use this lib. Is this issue still persist?

**Comment by sangilipandian** [comment] 2024-12-20 08:41
@Crazelu Any update on this issue? I'm also facing it..

**Comment by Crazelu** [comment] 2024-12-20 13:39
I still need concrete steps to reproduce this issue.

Here’s what I’ve gathered so far:

1. The overlay isn’t dismissed along with the keyboard

The reproduction steps for this are straightforward.
Is there more to this issue that I should know about?

I’m planning to take a look over the weekend

**Comment by sangilipandian** [comment] 2024-12-20 15:18
Yes, you're right. Here is the small demo. 

Also, Is is possible to show overlay with default data when type the '@' ? Currently it displays the overlay after starting type text. Please advice on this. 

Appreciate your effort @Crazelu 

[Issue.webm](https://github.com/user-attachments/assets/c40c5f9b-5bef-49d3-8a94-957757777998)

**Comment by Crazelu** [comment] 2024-12-20 15:59
Alright
I’m going to try to track focus changes and then recompute the placement of the overlay when that event is fired.

For the display of the overlay on trigger, I’ll introduce an enum to opt into this behavior. I’ve received the same comment from other people as well but most people seem to be fine with the default behavior. So this won’t be a breaking change.

**Comment by Crazelu** [comment] 2024-12-22 17:26
@sangilipandian you can specify the overlay height

**Comment by sangilipandian** [comment] 2024-12-26 05:30
> Alright I’m going to try to track focus changes and then recompute the placement of the overlay when that event is fired.
> 
> For the display of the overlay on trigger, I’ll introduce an enum to opt into this behavior. I’ve received the same comment from other people as well but most people seem to be fine with the default behavior. So this won’t be a breaking change.

@Crazelu Hey, sorry to disturb you on Holidays.  Is there any update on this issue?

**Comment by Crazelu** [comment] 2024-12-31 10:34
This issue has now been fixed in [v2.3.0](https://pub.dev/packages/fluttertagger/versions/2.3.0).
@sangilipandian I've also introduced a `TriggerStrategy` enum which you can use show the overlay immediately a trigger character (e.g "@") is typed. Use `triggerStrategy: TriggerStrategy.eager`

**Comment by sangilipandian** [comment] 2024-12-31 10:43
Thanks a lot @Crazelu 
Tested the changes and its working as expected.

**Comment by Crazelu** [comment] 2024-12-31 11:31
You're welcome.
I'll close this issue now

**Closed by Crazelu** 2024-12-31 11:31 UTC
