### ISSUE TITLE
seems only support English text

### ISSUE THREAD

**Issue by Amber916Young** [Crazelu/fluttertagger#7] opened 2024-07-30 16:00 UTC
The English text is working, but other languages cannot be detected.

**Comment by Crazelu** [comment] 2024-07-30 17:47
@Amber916Young can you describe the issue better and perhaps include some code to reproduce your issue?

**Comment by Amber916Young** [comment] 2024-07-30 18:23
Hi, Thank you for your prompt response.
When I input #hello, the widget correctly detects the keyword "hello". However, if I input #尼hello, the system fails to extract the tag "尼hello".

**Comment by Crazelu** [comment] 2024-07-30 19:05
This is probably because of the default regex pattern for allowed search characters (`^[a-zA-Z-]*$'`) which only includes letters of the English alphabet. You can allow more characters by specifying `searchRegex` for the `FlutterTagger` widget.

**Comment by Amber916Young** [comment] 2024-07-30 19:07
yes, I just noticed that parameter, anyway, thanks for replying!

**Comment by Crazelu** [comment] 2024-07-30 19:12
Anytime!

Closing this issue now since it is resolved.
Please re-open if you still have related issues.

**Closed by Crazelu** 2024-07-30 19:12 UTC
